[package]
name = "minesweep_rs"
version = "0.1.0"
authors = ["Stephan Göppentin <dedda102@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
colored = "2.0"
rand = "0.7"

